# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: mkronvold.Sunglasses
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - sunglasses
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mkronvold/sunglasses/releases/download/v1.0.0/Sunglasses.exe
    InstallerSha256: 575CEC53D2D3B95291F24F502635DC0F4F05BC2313A850EB148E30858AF0D3FB
ManifestType: installer
ManifestVersion: 1.6.0
